#!/usr/bin/env bash
# Assemble the Bohrium job payload for the pipeline_merge domain-integration run
# over the five minibatch papers test1..test5, then submit (or dry-run) it.
#
#   ./stage_and_submit.sh stage            # build the payload at STAGE_DIR
#   ./stage_and_submit.sh dry-run          # validate the Bohrium payload
#   ./stage_and_submit.sh submit           # real submission (billable)
#   ./stage_and_submit.sh smoke            # environment check, no pipeline run
#
# The merge step reads the compiled Gaia Packages (gaia.ir) plus each paper's
# formalization and knowledge index, so the payload carries data/minibatch/<p>/
# for the selected papers and a manifest generated by build_input_manifest.py.
# Unlike the single-paper driver this is ONE job for all five papers: the domain
# graph is produced jointly, not per paper.
set -euo pipefail

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$SELF_DIR/../.." && pwd)"

PROJECT_ID="${PROJECT_ID:-4655935}"
MACHINE_TYPE="${MACHINE_TYPE:-c8_m32_cpu}"
IMAGE_ADDRESS="${IMAGE_ADDRESS:-registry.dp.tech/dptech/ubuntu:ubuntu24.04-py3.12}"
# Domain integration is LLM-heavy over 5 papers; allow a generous wall clock.
MAX_RUN_TIME="${MAX_RUN_TIME:-480}"
RESULT_ROOT="${RESULT_ROOT:-/personal/bohr_merge_test1-5}"

PAPERS=(${PAPERS:-test1 test2 test3 test4 test5})
MANIFEST_NAME="${MANIFEST_NAME:-test1-5}"
STAGE_DIR="${STAGE_DIR:-/tmp/gaia_bohr_merge_${MANIFEST_NAME}}"

die() { echo "error: $*" >&2; exit 1; }

copy_code() {
  local dest="$1"
  rsync -a \
    --exclude '__pycache__/' --exclude '.pytest_cache/' --exclude '.DS_Store' \
    --exclude 'tests/' \
    "$REPO/agent/" "$dest/agent/"

  mkdir -p "$dest/pipelines/single_paper" "$dest/pipelines/merge"
  rsync -a \
    --exclude '__pycache__/' --exclude '.pytest_cache/' --exclude '.DS_Store' \
    --exclude 'tests/' \
    "$REPO/pipelines/single_paper/" "$dest/pipelines/single_paper/"
  rsync -a \
    --exclude '__pycache__/' --exclude '.pytest_cache/' --exclude '.DS_Store' \
    --exclude 'tests/' \
    "$REPO/pipelines/merge/" "$dest/pipelines/merge/"
  # The cleaner writes into claim_cleaner/data; ship the directory empty so the
  # remote run does not inherit local working outputs.
  rm -rf "$dest/pipelines/single_paper/agent_pipeline_v2/claim_cleaner/data"
  mkdir -p "$dest/pipelines/single_paper/agent_pipeline_v2/claim_cleaner/data"

  cp "$REPO/run_pipeline.sh" "$dest/"
  cp "$SELF_DIR/job_run.sh" "$dest/"
  chmod +x "$dest/job_run.sh" "$dest/run_pipeline.sh"
}

copy_paper_data() {
  local dest="$1" paper="$2" source="$REPO/data/minibatch/$paper"
  [[ -d "$source" ]] || die "paper directory not found: $source"
  mkdir -p "$dest/data/minibatch/$paper"
  local filename
  for filename in gaia.ir.json formalization.json knowledge.index.json; do
    [[ -f "$source/$filename" ]] || die "missing merge input: $source/$filename"
    cp "$source/$filename" "$dest/data/minibatch/$paper/"
  done
}

write_manifest() {
  local dest="$1"
  python3 "$SELF_DIR/build_input_manifest.py" "${PAPERS[@]}" \
    --out "$dest/manifests/$MANIFEST_NAME.json"
}

write_provenance() {
  local out="$STAGE_DIR/PROVENANCE.txt"
  {
    echo "pipeline_name=merge (pipeline-merge-test1-5)"
    echo "staged_at_utc=$(date -u +%FT%TZ)"
    echo "local_repo=$REPO"
    echo "local_git_commit=$(git -C "$REPO" rev-parse HEAD)"
    echo "local_git_dirty=$(test -n "$(git -C "$REPO" status --porcelain)" && echo true || echo false)"
    echo "pipeline_config=pipelines/merge/pipeline.test1-5.json"
    echo "pipeline_config_sha256=$(shasum -a 256 "$STAGE_DIR/pipelines/merge/pipeline.test1-5.json" | awk '{print $1}')"
    echo "papers=${PAPERS[*]}"
    echo
    echo "--- pipeline source hashes (sha256) ---"
    ( cd "$STAGE_DIR" && find agent/pipeline_harness pipelines/single_paper/agent_pipeline_v2 pipelines/merge/pipeline_merge \
        -name '*.py' -not -path '*/data/*' | LC_ALL=C sort | xargs shasum -a 256 )
    echo
    echo "--- input hashes (sha256) ---"
    ( cd "$STAGE_DIR" && shasum -a 256 data/minibatch/*/gaia.ir.json data/minibatch/*/formalization.json data/minibatch/*/knowledge.index.json 2>/dev/null )
  } > "$out"
}

stage() {
  echo "== staging ${PAPERS[*]} -> $STAGE_DIR"
  rm -rf "$STAGE_DIR"
  mkdir -p "$STAGE_DIR/manifests"
  copy_code "$STAGE_DIR"
  local paper
  for paper in "${PAPERS[@]}"; do
    copy_paper_data "$STAGE_DIR" "$paper"
  done
  write_manifest "$STAGE_DIR"
  write_provenance
  echo "== staged $(du -sh "$STAGE_DIR" | awk '{print $1}')"
}

write_job_json() {
  local dest="$1"
  cat > "$dest" <<EOF
{
  "job_name": "gaia-merge-${MANIFEST_NAME}",
  "command": "mkdir -p results && bash job_run.sh > results/merge.driver.log 2>&1",
  "log_file": "results/merge.driver.log",
  "backward_files": ["results/"],
  "project_id": $PROJECT_ID,
  "machine_type": "$MACHINE_TYPE",
  "image_address": "$IMAGE_ADDRESS",
  "max_run_time": $MAX_RUN_TIME,
  "result_path": "$RESULT_ROOT"
}
EOF
}

ensure_stage() {
  [[ -f "$STAGE_DIR/manifests/$MANIFEST_NAME.json" && -d "$STAGE_DIR/pipelines/merge" ]] || stage
}

submit() {
  local mode="$1"
  ensure_stage
  local job_json="$STAGE_DIR/job.merge.json"
  write_job_json "$job_json"
  echo "== $mode merge (payload $(du -sh "$STAGE_DIR" | awk '{print $1}'))"
  if [[ "$mode" == "dry-run" ]]; then
    bohr job submit -i "$job_json" --input_directory "$STAGE_DIR" --dry-run -o json
  else
    bohr job submit -i "$job_json" --input_directory "$STAGE_DIR" -y -o json
  fi
}

submit_smoke() {
  ensure_stage
  local job_json="$STAGE_DIR/job.smoke.json"
  cat > "$job_json" <<EOF
{
  "job_name": "gaia-merge-smoke",
  "command": "mkdir -p results && bash job_run.sh smoke > results/smoke.driver.log 2>&1",
  "log_file": "results/smoke.driver.log",
  "backward_files": ["results/"],
  "project_id": $PROJECT_ID,
  "machine_type": "$MACHINE_TYPE",
  "image_address": "$IMAGE_ADDRESS",
  "max_run_time": 30,
  "result_path": "$RESULT_ROOT/_smoke"
}
EOF
  echo "== submit smoke (environment check only, no pipeline run)"
  bohr job submit -i "$job_json" --input_directory "$STAGE_DIR" -y -o json
}

case "${1:-}" in
  stage) stage ;;
  dry-run) submit dry-run ;;
  submit) submit submit ;;
  smoke) submit_smoke ;;
  *)
    echo "usage: $0 {stage|dry-run|submit|smoke}" >&2
    exit 2
    ;;
esac
